table = 'auth_permission'
fields = ['id', 'name', 'content_type_id', 'codename']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1L, u'Can add permission', 1L, u'add_permission']
[2L, u'Can change permission', 1L, u'change_permission']
[3L, u'Can delete permission', 1L, u'delete_permission']
[4L, u'Can add group', 2L, u'add_group']
[5L, u'Can change group', 2L, u'change_group']
[6L, u'Can delete group', 2L, u'delete_group']
[7L, u'Can add user', 3L, u'add_user']
[8L, u'Can change user', 3L, u'change_user']
[9L, u'Can delete user', 3L, u'delete_user']
[10L, u'Can add message', 4L, u'add_message']
[11L, u'Can change message', 4L, u'change_message']
[12L, u'Can delete message', 4L, u'delete_message']
[13L, u'Can add content type', 5L, u'add_contenttype']
[14L, u'Can change content type', 5L, u'change_contenttype']
[15L, u'Can delete content type', 5L, u'delete_contenttype']
[16L, u'Can add session', 6L, u'add_session']
[17L, u'Can change session', 6L, u'change_session']
[18L, u'Can delete session', 6L, u'delete_session']
[19L, u'Can add site', 7L, u'add_site']
[20L, u'Can change site', 7L, u'change_site']
[21L, u'Can delete site', 7L, u'delete_site']
[22L, u'Can add log entry', 8L, u'add_logentry']
[23L, u'Can change log entry', 8L, u'change_logentry']
[24L, u'Can delete log entry', 8L, u'delete_logentry']
[25L, u'Can add concello', 9L, u'add_concello']
[26L, u'Can change concello', 9L, u'change_concello']
[27L, u'Can delete concello', 9L, u'delete_concello']
[28L, u'Can add lugar', 10L, u'add_lugar']
[29L, u'Can change lugar', 10L, u'change_lugar']
[30L, u'Can delete lugar', 10L, u'delete_lugar']
[31L, u'Can add modelo forestal', 11L, u'add_modeloforestal']
[32L, u'Can change modelo forestal', 11L, u'change_modeloforestal']
[33L, u'Can delete modelo forestal', 11L, u'delete_modeloforestal']
[37L, u'Can add finca', 13L, u'add_finca']
[38L, u'Can change finca', 13L, u'change_finca']
[39L, u'Can delete finca', 13L, u'delete_finca']
[40L, u'Can add certificacion', 14L, u'add_certificacion']
[41L, u'Can change certificacion', 14L, u'change_certificacion']
[42L, u'Can delete certificacion', 14L, u'delete_certificacion']
[43L, u'Can add especie', 15L, u'add_especie']
[44L, u'Can change especie', 15L, u'change_especie']
[45L, u'Can delete especie', 15L, u'delete_especie']
[46L, u'Can add viaxe camion', 16L, u'add_viaxecamion']
[47L, u'Can change viaxe camion', 16L, u'change_viaxecamion']
[48L, u'Can delete viaxe camion', 16L, u'delete_viaxecamion']
[49L, u'Can add tala', 17L, u'add_tala']
[50L, u'Can change tala', 17L, u'change_tala']
[51L, u'Can delete tala', 17L, u'delete_tala']
[52L, u'Can add tipo empresa', 18L, u'add_tipoempresa']
[53L, u'Can change tipo empresa', 18L, u'change_tipoempresa']
[54L, u'Can delete tipo empresa', 18L, u'delete_tipoempresa']
[55L, u'Can add empresa', 19L, u'add_empresa']
[56L, u'Can change empresa', 19L, u'change_empresa']
[57L, u'Can delete empresa', 19L, u'delete_empresa']
[58L, u'Can add empleado', 20L, u'add_empleado']
[59L, u'Can change empleado', 20L, u'change_empleado']
[60L, u'Can delete empleado', 20L, u'delete_empleado']
[61L, u'Can add camion', 21L, u'add_camion']
[62L, u'Can change camion', 21L, u'change_camion']
[63L, u'Can delete camion', 21L, u'delete_camion']
[64L, u'Can add tipo operacion', 22L, u'add_tipooperacion']
[65L, u'Can change tipo operacion', 22L, u'change_tipooperacion']
[66L, u'Can delete tipo operacion', 22L, u'delete_tipooperacion']
[67L, u'Can add factura', 23L, u'add_factura']
[68L, u'Can change factura', 23L, u'change_factura']
[69L, u'Can delete factura', 23L, u'delete_factura']
[70L, u'Can add detalle factura', 24L, u'add_detallefactura']
[71L, u'Can change detalle factura', 24L, u'change_detallefactura']
[72L, u'Can delete detalle factura', 24L, u'delete_detallefactura']
[73L, u'Can add recibo', 25L, u'add_recibo']
[74L, u'Can change recibo', 25L, u'change_recibo']
[75L, u'Can delete recibo', 25L, u'delete_recibo']
[76L, u'Can add detalle recibo', 26L, u'add_detallerecibo']
[77L, u'Can change detalle recibo', 26L, u'change_detallerecibo']
[78L, u'Can delete detalle recibo', 26L, u'delete_detallerecibo']
[79L, u'Can add migration history', 27L, u'add_migrationhistory']
[80L, u'Can change migration history', 27L, u'change_migrationhistory']
[81L, u'Can delete migration history', 27L, u'delete_migrationhistory']
[82L, u'Can add parroquia', 28L, u'add_parroquia']
[83L, u'Can change parroquia', 28L, u'change_parroquia']
[84L, u'Can delete parroquia', 28L, u'delete_parroquia']
[85L, u'Can add servizo forestal tipo', 29L, u'add_servizoforestaltipo']
[86L, u'Can change servizo forestal tipo', 29L, u'change_servizoforestaltipo']
[87L, u'Can delete servizo forestal tipo', 29L, u'delete_servizoforestaltipo']
[88L, u'Can add provincia', 30L, u'add_provincia']
[89L, u'Can change provincia', 30L, u'change_provincia']
[90L, u'Can delete provincia', 30L, u'delete_provincia']
[91L, u'Can add tipo iva', 31L, u'add_tipoiva']
[92L, u'Can change tipo iva', 31L, u'change_tipoiva']
[93L, u'Can delete tipo iva', 31L, u'delete_tipoiva']
[94L, u'Can add unidade', 32L, u'add_unidade']
[95L, u'Can change unidade', 32L, u'change_unidade']
[96L, u'Can delete unidade', 32L, u'delete_unidade']
[97L, u'Can add bookmark', 33L, u'add_bookmark']
[98L, u'Can change bookmark', 33L, u'change_bookmark']
[99L, u'Can delete bookmark', 33L, u'delete_bookmark']
[100L, u'Can add dashboard preferences', 34L, u'add_dashboardpreferences']
[101L, u'Can change dashboard preferences', 34L, u'change_dashboardpreferences']
[102L, u'Can delete dashboard preferences', 34L, u'delete_dashboardpreferences']
[103L, u'Can add memento', 35L, u'add_memento']
[104L, u'Can change memento', 35L, u'change_memento']
[105L, u'Can delete memento', 35L, u'delete_memento']
[106L, u'Can add monte', 36L, u'add_monte']
[107L, u'Can change monte', 36L, u'change_monte']
[108L, u'Can delete monte', 36L, u'delete_monte']
[109L, u'Can add revision', 37L, u'add_revision']
[110L, u'Can change revision', 37L, u'change_revision']
[111L, u'Can delete revision', 37L, u'delete_revision']
[112L, u'Can add version', 38L, u'add_version']
[113L, u'Can change version', 38L, u'change_version']
[114L, u'Can delete version', 38L, u'delete_version']
[115L, u'Can add provincia', 39L, u'add_provincia']
[116L, u'Can change provincia', 39L, u'change_provincia']
[117L, u'Can delete provincia', 39L, u'delete_provincia']
]
