table = 'django_content_type'
fields = ['id', 'name', 'app_label', 'model']
#default item format: "fieldname":("type", "value")
default = {}
records = [
[1L, u'permission', u'auth', u'permission']
[2L, u'group', u'auth', u'group']
[3L, u'user', u'auth', u'user']
[4L, u'message', u'auth', u'message']
[5L, u'content type', u'contenttypes', u'contenttype']
[6L, u'session', u'sessions', u'session']
[7L, u'site', u'sites', u'site']
[8L, u'log entry', u'admin', u'logentry']
[9L, u'concello', u'fincas', u'concello']
[10L, u'lugar', u'fincas', u'lugar']
[11L, u'modelo forestal', u'fincas', u'modeloforestal']
[13L, u'finca', u'fincas', u'finca']
[14L, u'certificacion', u'fincas', u'certificacion']
[15L, u'especie', u'fincas', u'especie']
[16L, u'viaxe camion', u'fincas', u'viaxecamion']
[17L, u'tala', u'fincas', u'tala']
[18L, u'tipo empresa', u'empresas', u'tipoempresa']
[19L, u'empresa', u'empresas', u'empresa']
[20L, u'empleado', u'empresas', u'empleado']
[21L, u'camion', u'empresas', u'camion']
[22L, u'tipo operacion', u'empresas', u'tipooperacion']
[23L, u'factura', u'empresas', u'factura']
[24L, u'detalle factura', u'empresas', u'detallefactura']
[25L, u'recibo', u'empresas', u'recibo']
[26L, u'detalle recibo', u'empresas', u'detallerecibo']
[27L, u'migration history', u'south', u'migrationhistory']
[28L, u'parroquia', u'fincas', u'parroquia']
[29L, u'servizo forestal tipo', u'fincas', u'servizoforestaltipo']
[30L, u'provincia', u'empresas', u'provincia']
[31L, u'tipo iva', u'empresas', u'tipoiva']
[32L, u'unidade', u'fincas', u'unidade']
[33L, u'bookmark', u'menu', u'bookmark']
[34L, u'dashboard preferences', u'dashboard', u'dashboardpreferences']
[35L, u'memento', u'memento', u'memento']
[36L, u'monte', u'fincas', u'monte']
[37L, u'revision', u'reversion', u'revision']
[38L, u'version', u'reversion', u'version']
[39L, u'provincia', u'fincas', u'provincia']
]
