# Generated by Django 3.0.5 on 2020-06-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(choices=[(1, 'Same Owner'), (2, 'Different Owner')])),
            ],
        ),
        migrations.CreateModel(
            name='BorderFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poligon', models.IntegerField(blank=True, default=None, null=True)),
                ('parcela', models.IntegerField(blank=True, default=None, null=True)),
                ('agregado', models.IntegerField(blank=True, default=None, null=True)),
                ('zona', models.IntegerField(blank=True, default=None, null=True)),
                ('ref_catastral', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionCorta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Condicion')),
            ],
        ),
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comezo', models.DateField(blank=True)),
                ('final', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('number', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('deedType', models.IntegerField(choices=[(1, 'Compraventa'), (2, 'Herencia')], default=1)),
                ('obs', models.TextField(blank=True)),
                ('inscription', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('obs', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='EventFincaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventfinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.EventFinca')),
            ],
        ),
        migrations.CreateModel(
            name='EventFincaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.IntegerField()),
                ('obs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poligon', models.IntegerField()),
                ('parcela', models.IntegerField()),
                ('agregado', models.IntegerField(blank=True)),
                ('zona', models.IntegerField(blank=True)),
                ('superficie', models.FloatField(blank=True)),
                ('codigo_ref', models.CharField(blank=True, default='', max_length=255)),
                ('ref_catastral', models.CharField(blank=True, default='', max_length=255)),
                ('pasado', models.NullBooleanField()),
                ('obs', models.TextField(blank=True)),
                ('property_title', models.TextField(blank=True)),
                ('fecha_plantacion', models.DateField(blank=True)),
                ('densidad', models.FloatField(blank=True)),
                ('ha_matorral', models.FloatField(blank=True)),
                ('ha_prado', models.FloatField(blank=True)),
                ('ha_construidas', models.FloatField(blank=True)),
                ('ha_total', models.FloatField(blank=True)),
                ('paraje_catastral', models.CharField(blank=True, default='', max_length=255)),
                ('cultivo_catastral', models.CharField(blank=True, default='', max_length=255)),
                ('intensidad_catastral', models.CharField(blank=True, default='', max_length=255)),
                ('calificacion_catastral', models.CharField(blank=True, default='', max_length=255)),
                ('borders', models.ManyToManyField(through='fincas.Border', to='fincas.BorderFinca')),
                ('concello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Concello')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finca_dono_set', to='empresas.Empresa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finca_empresa_set', to='empresas.Empresa')),
                ('events', models.ManyToManyField(through='fincas.EventFincaLog', to='fincas.EventFinca')),
            ],
            options={
                'verbose_name': 'Parcela',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('concello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Concello')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloForestal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('obs', models.TextField()),
            ],
            options={
                'verbose_name': 'Modelo Forestal',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServizoForestalTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comezo', models.DateField(blank=True)),
                ('final', models.DateField(blank=True)),
                ('permiso', models.DateField(blank=True)),
                ('entradaGrupo', models.DateField(blank=True)),
                ('codigoPECL', models.CharField(blank=True, max_length=100)),
                ('dataPECL', models.DateField(blank=True)),
                ('codigoNORFOR', models.CharField(blank=True, max_length=100, verbose_name='NORFOR')),
                ('dataPECLsaida', models.DateField(blank=True, null=True, verbose_name='Alb. Saida PECL')),
                ('tm_permiso', models.FloatField(blank=True, default=0, verbose_name='Pes permiso')),
                ('m2_permiso', models.FloatField(default=0, verbose_name='m3 permiso')),
                ('altura', models.IntegerField(blank=True, default=0, null=True)),
                ('obs', models.TextField(blank=True)),
                ('condicions', models.ManyToManyField(blank=True, null=True, to='fincas.CondicionCorta')),
                ('empresas', models.ManyToManyField(blank=True, null=True, to='empresas.Empresa')),
                ('finca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Finca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.ServizoForestalTipo')),
            ],
            options={
                'verbose_name': 'Servizo Forestal',
            },
        ),
        migrations.CreateModel(
            name='TipoCorta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Tipo de corta')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abrv', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ViaxeCamion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_talonario', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº talonario')),
                ('dia', models.DateField(blank=True, null=True)),
                ('tm', models.FloatField(blank=True, null=True)),
                ('estereo', models.FloatField(blank=True, null=True)),
                ('metrocubico', models.FloatField(blank=True, null=True)),
                ('obs', models.TextField(blank=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Camion')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
                ('origen', models.ManyToManyField(blank=True, null=True, related_name='origen', to='fincas.Tala')),
            ],
        ),
        migrations.AddField(
            model_name='tala',
            name='tipocorta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.TipoCorta'),
        ),
        migrations.AddField(
            model_name='tala',
            name='viaxecamions',
            field=models.ManyToManyField(blank=True, null=True, related_name='viaxecamions', to='fincas.ViaxeCamion'),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(choices=[(1, 'Same Owner'), (2, 'Different Owner')])),
                ('from_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_parcel', to='fincas.Finca')),
                ('to_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_parcel', to='fincas.Finca')),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('concello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Concello')),
            ],
        ),
        migrations.CreateModel(
            name='Monte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('concello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Concello')),
                ('lugar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Lugar')),
                ('parroquia', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Parroquia')),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='parroquia',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Parroquia'),
        ),
        migrations.AddField(
            model_name='finca',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Lugar'),
        ),
        migrations.AddField(
            model_name='finca',
            name='modeloforestal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.ModeloForestal', verbose_name='Modelo Forestal'),
        ),
        migrations.AddField(
            model_name='finca',
            name='monte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Monte'),
        ),
        migrations.AddField(
            model_name='finca',
            name='relationships',
            field=models.ManyToManyField(related_name='_finca_relationships_+', through='fincas.Relationship', to='fincas.Finca'),
        ),
        migrations.AddField(
            model_name='finca',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Unidade'),
        ),
        migrations.CreateModel(
            name='EventFincaTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventfinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.EventFinca')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Finca')),
            ],
        ),
        migrations.AddField(
            model_name='eventfincalog',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Finca'),
        ),
        migrations.AddField(
            model_name='eventfinca',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.EventFincaType'),
        ),
        migrations.CreateModel(
            name='DeedSellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Deed')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DeedFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Deed')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Finca')),
            ],
        ),
        migrations.AddField(
            model_name='deed',
            name='fincas',
            field=models.ManyToManyField(null=True, through='fincas.DeedFinca', to='fincas.Finca'),
        ),
        migrations.AddField(
            model_name='deed',
            name='sellers',
            field=models.ManyToManyField(null=True, related_name='sellers', through='fincas.DeedSellers', to='empresas.Empresa'),
        ),
        migrations.AddField(
            model_name='concello',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Provincia'),
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio_documentacion', models.DateField()),
                ('aprobacion', models.DateField()),
                ('finca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Finca')),
            ],
        ),
        migrations.AddField(
            model_name='borderfinca',
            name='concello',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Concello'),
        ),
        migrations.AddField(
            model_name='borderfinca',
            name='lugar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.Lugar'),
        ),
        migrations.AddField(
            model_name='border',
            name='borderFinca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.BorderFinca'),
        ),
        migrations.AddField(
            model_name='border',
            name='finca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fincas.Finca'),
        ),
        migrations.AlterUniqueTogether(
            name='finca',
            unique_together={('concello', 'poligon', 'parcela', 'zona')},
        ),
    ]
