# Generated by Django 4.2.16 on 2025-08-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('fincas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='servizo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fincas.tala'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tipo_irpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_irpf_set', to='empresas.tipoiva'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='tipo_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_iva_set', to='empresas.tipoiva'),
        ),
        migrations.AddField(
            model_name='camion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
